// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WebServiceBooking.Backend.Data;

namespace WebServiceBooking.Backend.Migrations
{
    [DbContext(typeof(WebDBContext)), Migration("20220601153405_CreateDB_initall_20220601LOC")]
    internal abstract class CreateDB_initall_20220601LOCBase
    {
        protected abstract override void BuildTargetModel(ModelBuilder modelBuilder);
    }
}